language: java

jdk:
  - openjdk11
  

addons:
  sonarcloud:
    projectKey: "cloud-event-api"
    organization: "sigrist-github"
 

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar